name: build
on:
  push:
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Build
        run: make docker-build
        env:
          SERVER_NAME: sqlite-cloudrun
